### ISSUE TITLE
[Feature]: excludeElements

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#160]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- Package name: @modern-kit/utils/array

<br />

### **Overview**

첫 번째 인자로 주어진 배열에서 주어진 값을 제거한 새로운 배열을 반환합니다.

```ts
const arr = [1, 2, 3, 3, 4, 5];
const excludedArray = excludeElements(arr, 3, 4);
// [1, 2, 5]
```

**Comment by Collection50** [comment]
안녕하세요 @ssi02014 님

제가 이슈를 할당받아도 될까요??

**Comment by ssi02014** [comment]
@Collection50 넵! 그럼요 감사합니다🤗👍

**Comment by ssi02014** [comment]
@Collection50 참고로 기존에 참고한 아이디어는 lodash의 without입니다. 자주 사용 할 유틸 함수라 생각해서 직접 구현해보고자 하였습니다 참고해서 작업해주시면 감사드립니다 🤗
https://lodash.com/docs/4.17.15#without

**Comment by Collection50** [comment]
> @Collection50 참고로 기존 아이디어는 lodash의 without입니다. 배열을 다룰 때 자주 사용 할 수 있는 유틸 함수라 생각해서 직접 구현해보고 다른 분들께 레퍼런스로 제공하고자 하였습니다 참고해서 작업해주시면 감사드립니다 🤗 https://lodash.com/docs/4.17.15#without

네 알겠습니다 !!
