### ISSUE TITLE
[Feature]: OutsideClick

### ISSUE THREAD

**Issue by Collection50** [modern-agile-team/modern-kit#162]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- Package name: @modern-kit/react

<br />

### **Overview**
`useOnOutsideClick`의 기능을 선언적으로 처리하는 `OutsideClick` 컴포넌트를 구현합니다.

```jsx
<OutsideClick callback={() => console.log('outside clicked!')}>
  <div>something</div>
</OutsideClick>
```

**Comment by ssi02014** [comment]
@Collection50 감사합니다 !! 좋은 유틸 컴포넌트라고 생각됩니다 🤗
관련된 훅이 useOnClickOutside 이 있긴한데 함께 활용될 수 있는 부분일까요? 
작업해주시면 검토해보겠습니다!!

**Comment by Collection50** [comment]
> @Collection50 감사합니다 !! 좋은 유틸 컴포넌트라고 생각됩니다 🤗 관련된 훅이 `useOnClickOutside` 이 있긴한데 함께 활용될 수 있는 부분일까요? 작업해주시면 검토해보겠습니다!!

네 함께 사용해 구현하려고 합니다 !

**Comment by ssi02014** [comment]
@Collection50 감사합니다! 작업 중에 궁금하신 부분있으면 댓글남 겨주시면 답변드리도록 하겠습니다 🙏
