### ISSUE TITLE
[Fix]: string/repeatCharacters

### ISSUE THREAD

**Issue by hoonloper** [modern-agile-team/modern-kit#169]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지

- Package name: `utils`

<br />

### **Overview**

string util 중에서 `repeatCharacters` 함수 성능에 대한 아이디어입니다.
현재 순회하면서 `+` 연산을 통해 문자열을 더해주는데 이것을 배열로 활용해보면 어떨까에 대한 의견이에요.

- **javascript의 String 메모리 관리를 어떻게 하는지 기억이 가물가물하지만, 동일한 String에 대해 같은 메모리를 참조하고 있다면 `+` 연산이 이뤄질 때마다 새로운 메모리에 할당하는 과정이 반복적으로 발생할 것**입니다.
- 배열의 경우 각 문자열을 참조하는 주소를 배열에 담고 마지막에 join을 통해 합칠 때만 새로운 메모리에 참조하는 과정을 통해 성능이 개선되는 것으로 **'추측'**하고 있는데 틀린 내용이 있으면 피드백 부탁드립니다!

실제 성능은 문자열이 길어질수록 배열 순회가 더 빠른 것으로 나타나고 있습니다.

```js
  const testStringLength = 100000000; // 테스트할 문자열의 길이

  // 문자열 연산자 사용
  const startTimeConcat = performance.now();
  let resultConcat = '';
  for (let i = 0; i < testStringLength; i++) {
    resultConcat += 'a';
  }
  const endTimeConcat = performance.now();

  // 배열에 요소 추가 후 join 메서드 사용
  const startTimePushJoin = performance.now();
  const resultArray = [];
  for (let i = 0; i < testStringLength; i++) {
    resultArray.push('a');
  }
  const resultPushJoin = resultArray.join('');
  const endTimePushJoin = performance.now();

  console.log(`Using + operator: ${endTimeConcat - startTimeConcat}ms`);
  console.log(
    `Using push and join: ${endTimePushJoin - startTimePushJoin}ms`
  );
```

![image](https://github.com/modern-agile-team/modern-kit/assets/78959175/7a1fbf55-fe4d-43fe-aef0-7cecea67221c)

**Comment by ssi02014** [comment]
@hoonloper 동작은 동일한데 배열을 활용했을 때 성능이 더 좋다면 배열을 활용하는 방향으로 진행해도 될 것 같습니다 🤗

단, 실제로 테스트 코드로 제안주신 10000000만큼 복사하는 케이스는 흔하지는 않기 때문에 어느정도 성능이슈는 감안해도 괜찮다고 생각합니다! 따라서, 배열로 전환했을 때 기존보다 가독성이 떨어진다면 이 부분은 고려가 필요합니다! 🙏

**Comment by hoonloper** [comment]
가독성에 대한 부분은 실제 로직을 작성했을 때 크게 차이가 나진 않으나 명확함에 있어서는 `+`가 더 좋더라고요 ㅎㅎ!
트레이드 오프를 고려했을 때 사실 변경할 이유가 없긴 합니다 ㅋㅋ..
추후 문자열 연산이나 중복 순회하는 util 혹은 이 외 로직이 생긴다면 `+` 연산에 대한 컨텍스트 스위칭 비용도 고민해 보면 재미있을 거예요~

위와 같은 생각으로 PR이 아닌 issue로 만들었기에 closed되어도 상관 없습니다!🤓

**Comment by ssi02014** [comment]
> 가독성에 대한 부분은 실제 로직을 작성했을 때 크게 차이가 나진 않으나 명확함에 있어서는 `+`가 더 좋더라고요 ㅎㅎ! 트레이드 오프를 고려했을 때 사실 변경할 이유가 없긴 합니다 ㅋㅋ.. 추후 문자열 연산이나 중복 순회하는 util 혹은 이 외 로직이 생긴다면 `+` 연산에 대한 컨텍스트 스위칭 비용도 고민해 보면 재미있을 거예요~
> 
> 위와 같은 생각으로 PR이 아닌 issue로 만들었기에 closed되어도 상관 없습니다!🤓

좋습니다! 👍 나중에 또 좋은 아이디어, 의견이 있으면 알려주세요! 해당 이슈도 그때 다시 열어주시면 감사드려요! 🤗
