### ISSUE TITLE
[Feature]: isReference, isPlainObject

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#218]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- Package name: @modern-kit/utils/validator

<br />

### **Overview**

인자로 받은 value가 원시값이 아닌 참조형인지 판단하는 `isReference` 함수와 일반 객체인지 판단하는 `isPlainObject`

```ts
isReference({}); // true
isReference([]); // true
isReference(new Set()); // true
isReference(new Map()); // true
```

```ts
isPlainObject({}); // true
isPlainObject([]); // false
isPlainObject(new Set()); // false
isPlainObject(new Map()); // false
```

**Comment by Gaic4o** [comment]
안녕하세요, 제가 `isReference`와 `isPlainObject` 유틸 함수를 구현해 보아도 될지 여쭙고 싶습니다!
감사합니다.

**Comment by ssi02014** [comment]
@Gaic4o 라이브러리에 관심을 가져주셔서 정말 감사합니다 👍 작업자 할당했씁니다.

1. isReference 는 사전에 작업된 [isPrimitive](https://github.com/modern-agile-team/modern-kit/blob/main/packages/utils/src/validator/isPrimitive/index.ts)을 활용해서 isPrimitive 호출의 부정`!isPrimitive()`로 반환하는 것을 생각했었고,  
2. isPlainObject는 isReference 작업 후에 `isReference() && value.constructor === Object`를 생각했었습니다.

위 생각은 참고용으로 봐주시고, 더 좋은 아이디어 및 방향성이 있다면 말씀해주세요! 감사합니다.
PR을 각각 생성해주시면 감사드릴게요!

**Comment by Gaic4o** [comment]
좋은 훅과 유틸 함수를 제공해 주셔서 많이 배우고 있습니다.
친절한 답변과 작업 할당에 감사드립니다. 안내해 주신 내용으로 구현해 보도록 하겠습니다!
