### ISSUE TITLE
[Feature]: isFloat

### ISSUE THREAD

**Issue by Sangminnn** [modern-agile-team/modern-kit#228]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name:  @modern-kit/utils/number

<br />

### **Overview**

주어진 인자가 유한한 부동소수점 숫자인지를 확인하는 함수입니다.

```typescript

isFloat(175.5) // true
isFloat(-15.5) // true

isFloat(100) // false
isFloat(-100) // false
isFloat(0) // false
isFloat(NaN) // false
isFloat(Infinity) // false
isFloat(-Infinity) // false
isFloat([]) // false
isFloat({}) // false
```

**Comment by Sangminnn** [comment]
@ssi02014 불필요한 기능이라고 생각되신다면 편하게 말씀주시면 감사드리겠습니다! :)

**Comment by ssi02014** [comment]
@Sangminnn 좋은 것 같습니다 !! 단 @modern-kit/utils/number 라는 새로운 폴더를 생성하는 것에 어떻게 생각하시나요?
숫자와 관련된 폴더를 따로 구성하면 좋을 것 같습니다 🤗
