### ISSUE TITLE
[Feature]: extractLetters

### ISSUE THREAD

**Issue by beberiche** [modern-agile-team/modern-kit#231]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils/string

<br />

### **Overview**
`extractLetters` 는 임의의 문자열에 대해 선택한 문자 속성만 반영한 새로운 문자열을 생성하여 반환하는 메서드 입니다.
기본 설정은 언어로 사용되는 문자(Letters)만 반영된 문자열을 반환합니다.

```javascript
const input = "Hello, 世界! 안녕하세요 123  مرحبا नमस्ते! $100 + 200 = 300";

const letterOnly = extractLetters(input);
console.log(letterOnly);  // "Hello世界안녕하세요مرحبانमस्ते"
```

옵션으로는 문자(letter) 포함/제거, 숫자(number) 포함/제거, 기호(Symbol) 포함/제거, 공백(space) 포함/제거 등이 있습니다. 

> 기호(Symbol)의 경우, 문자, 숫자, 공백을 제외한 문장부호, 특수문자 등을 포함합니다. (이모지는 포함하지 않습니다.)

```javascript
const input = "Hello, 世界! 안녕하세요 123  مرحبا नमस्ते! $100 + 200 = 300";

const numberOnly = extractLetters(input, { number: true });
console.log(numberOnly); // "123100200300"

const numberAndSymbol = extractLetters(input, { number: true, symbol: true });
console.log(numberAndSymbol); // ",!123!$100+200=300"

const letterAndSpace = extractLetters(input, { letter: true, space: true });
console.log(letterAndSpace); // "Hello 世界 안녕하세요  مرحبا नमसत     "

const letterAndSymbolAndSpace = extractLetters(input, { letter: true, symbol: true, space: true });
console.log(lettersAndSymbolAndSpace); // "Hello, 世界! 안녕하세요  مرحبا नमसत! $ +  = "
```

반영 여부 및 변경사항이 필요하다면 편하게 말씀해주세요 :)

**Comment by beberiche** [comment]
@ssi02014 label 하고 assignee 부여를 깜빡했네요!! 설정 부탁드리겠습니다!

**Comment by ssi02014** [comment]
@beberiche 이슈 등록 감사합니다 :)
함수 자체는 굉장히 유용해보이는데요!!
내일중으로 한번 검토 후에 의견 코멘트 남기도록 하겠습니다! 🙏🙏🙏🙏

**Comment by ssi02014** [comment]
@beberiche
`space`대신 `whiteSpace`는 어떨까요? 다른 유틸함수를 개발중인데 그쪽이랑 네이밍을 맞추고자 합니다
추가로 `symbol`과 `specialCharacters`도 네이밍이 약간 고민되는데.. 두 네이밍중 어떤게 더 나은 방향이라고 생각하실까요? (다른 개발중인 유틸 함수에서는 `specialCharacters` 사용중)

그 외에는 함수 기능, 인터페이스 모두 좋은 것 같습니다 ! 작업 진행해주셔도 좋을 것 같아요 🤗

**Comment by beberiche** [comment]
@ssi02014 
1. `space` 는 `whiteSpace` 로 대체해서 사용하겠습니다!
2.  일관성을 유지하기 위해 `spacialCharacters`를 사용하는 게 좋을 거 같습니다. 특수문자가 문자나 숫자 외에 컴퓨터에서 사용되는 기호 문자를 뜻한다고 합니다(출처 : 네이버 국어사전). 의미론적인 관점에서도 `specialCharacters` 가 적절하다고 느껴집니다.



우선 위의 방향으로 작업 진행해보겠습니다!!

**Comment by ssi02014** [comment]
@beberiche 넵 감사합니다 ~! 궁금하신 사항 있으시면 추가로 댓글 남겨주시고, PR올려주시면 검토 후 혹시 추가로 필요한 사항들 있다면 말씀드리겠씁니다~! 라이브러리에 관심을 가져주셔서 다시 한번 감사의 말씀 드립니다! 🙇🏻‍♂️
