### ISSUE TITLE
[Feature]: ScrollLock

### ISSUE THREAD

**Issue by Collection50** [modern-agile-team/modern-kit#234]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/react

<br />

### **Overview**

`useScrollLock` 컴포넌트에서 영감을 받았는데요 !
hook이 아닌 선언적 컴포넌트로 구현해도 좋을 것 같습니다 !

해당 이슈를 제가 받아도 될까요?

**Comment by Collection50** [comment]
@ssi02014 

두가지 방향성을 생각했습니다 !

1. `useScrollLock`과 동일한 인터페이스를 가져가되 선언형으로 변경한다.
2. `useScrollLock`보다 가벼운 인터페이스를 가져가면서 선언형으로 변경한다.

2번의 경우 아래와 같이 생각하고 있어요.

```tsx
interface Props {
  as?: React.ElementType;
  ref?: Ref<HTMLElement>;
}

// add forwardRef
function ScrollLock(props: Props) {
  // ref가 props로 전달되지 않는다면 ref 생성
  // or `useMergeRefs` 사용
}
```

<br/>

선언적으로 사용되는 특성상 `useScrollLock` `autoLock`을 사용하기는 어렵다고 판단했지만, 아래와 같은 사용법은 가능하다고 생각합니다 ! (사용성이 높을 것 같지는 않지만요 !)

```tsx
<ScrollLock>
  {(lock, unLock) => (
    <>
      <button onClick={() => lock()}>lock</button>
      <button onClick={() => unLock()}>unLock</button>
    </>
  )}
</ScrollLock>
```

**Comment by ssi02014** [comment]
정말 심플하게 아래와 같은 인터페이스는 어떻게 생각하시나요?
복잡한 인터페이스를 두지 않고, `isLock`으로 판단하는 방향입니다.

```tsx
<ScrollLock isLock={true | false}>
  <div>{/* ... */}</div>
</ScrollLock>
```

**Comment by Collection50** [comment]
@ssi02014 

컨트롤을 가능할 수 있게하는 점에서 좋은 것 같습니다 !
`ref` 하나만 더 추가하는 것은 어떻게 생각하시나요??

**Comment by ssi02014** [comment]
긍정적으로 받아주셔서 감사합니다! 
고민하면서 해당 컴포넌트는 정말 심플하게 인터페이스를 가져가도, 충분히 효율적인 컴포넌트가 될 수 있다고 생각했습니다 🙏

> ref 하나만 더 추가하는 것은 어떻게 생각하시나요??
네! 졸습니다! ScrollLock을 forwardRef로 구성해서 ref를 추가로 받는 방향 좋은 것 같습니다 🤗

**Comment by Collection50** [comment]
> @Collection50 의견을 긍정적으로 받아주셔서 감사합니다! 고민하면서 해당 컴포넌트는 정말 심플하게 인터페이스를 가져가도, 충분히 효율적인 컴포넌트가 될 수 있다고 생각했습니다 🙏
> 
> > ref 하나만 더 추가하는 것은 어떻게 생각하시나요??
> 
> 네! 좋습니다! ScrollLock을 forwardRef로 구성해서 ref를 추가로 받는 방향 좋은 것 같습니다 🤗

@ssi02014 님 다른 이슈를 할당받아도 괜찮을까요??
구현하고자 노력했으나 생각처럼 잘 동작하지 않는 부분이 많았습니다 🤣

**Comment by ssi02014** [comment]
@Collection50 어이쿠 작업하시느라 고생하셨습니다. 😭

추후에 ScrollLock 관련해서 좋은 아이디어가 생기면 이슈를 다시 열도록 하겠습니다 🙏🙏
