### ISSUE TITLE
[Feature]: intersectionWithDuplicates 내부 로직 개선

### ISSUE THREAD

**Issue by Sangminnn** [modern-agile-team/modern-kit#265]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils

<br />

### **Overview**

기존에 작업했던 `intersectionWithDuplicates` 의 내부 로직을 es-toolkit에서 간단하게 이야기나눈 내용에 따라 영감을 얻어 간결하게 수정하고자합니다.

**Comment by ssi02014** [comment]
@Sangminnn 
1. intersection을 중복을 포함하고 intersectionWithDuplicates 제거 후 intersectionWIthoutDuplicates으로 진행
2. intersectionWithDuplicates을 기반으로 중복이 없는 intersection을 작업할지..!! 어떤게 나을까요?

**Comment by Sangminnn** [comment]
@ssi02014 intersection을 생각했을때 저는 처음에 중복을 포함하지 않는 형태를 생각했었다보니 기본 형태인 intersection을 중복제거로 두고, intersectionWithDuplicates를 두는 2번 방향은 어떨까 생각이 들었네요!

**Comment by ssi02014** [comment]
> @ssi02014 intersection을 생각했을때 저는 처음에 중복을 포함하지 않는 형태를 생각했었다보니 기본 형태인 intersection을 중복제거로 두고, intersectionWithDuplicates를 두는 2번 방향은 어떨까 생각이 들었네요! 

@Sangminnn 아하 좋습니다!! 추가로 정말 작은 고민되는 부분이 intersection을 메인으로 두고 이를 파생시키는게 자연스러운지 굳이 intersection을 파생시키지 않아도 크게 상관없을지 부분이네요!! 이 부분은 어떻게 생각하실까용

**Comment by Sangminnn** [comment]
@ssi02014 개선을 생각했을때에는 사실 기존의 intersection과 intersectionWithDuplicates도 동일한 역할을 수행하다보니 간결한 코드화를 위해 intersectionWithDuplicates를 파생시켜 이로부터 중복제거하는 로직을 사용하고자 하였는데요!
정답은 없는 영역이다보니 더 좋은 의견이 있으실지 궁금합니다! 😄

**Comment by ssi02014** [comment]
> @ssi02014 개선을 생각했을때에는 사실 기존의 intersection과 intersectionWithDuplicates이 현재도 역할로서는 제대로 수행하다보니 역할을 바꾸기보다는 간결한 코드화를 위해 intersectionWithDuplicates를 파생시켜 이로부터 중복제거하는 로직을 사용하고자 하였는데요!
> 정답은 없는 영역이다보니 더 좋은 의견이 있으실지 궁금합니다! 😄 

생각한 방향대로 진행하시죠! 생각하신 방향이 리소스도 적고 크게 문제는 없다생각합니다
