### ISSUE TITLE
[Fix]: math 유틸 함수 for...of문 교체

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#279]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils

<br />

### **Overview**

https://leanylabs.com/blog/js-forEach-map-reduce-vs-for-for_of/
위 문서를 기반으로 math 유틸 함수(min, max)를 `for...of`문으로 교체합니다.

(그 외 모듈들은 작업 검토가 필요합니다.)

**Comment by ssi02014** [comment]
@Collection50 이슈 생성하였습니다

**Comment by Collection50** [comment]
제가 맡고 싶습니다 !!
