### ISSUE TITLE
[Feature]: forEachRight

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#298]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils/array

<br />

### **Overview**

기존 forEach와 다르게 오른쪽에서 부터 순회하면서 callback을 호출하는 함수입니다.

```ts
forEachRight([1, 2, 3], (el, index) => {
  console.log(el, index);
});
/* 
  3 2
  2 1
  1 0
*/
```

**Comment by Gaic4o** [comment]
이번에도 제가 forEachRight 유틸 함수 구현 해 봐도 괜찮을까요?!

**Comment by ssi02014** [comment]
@Gaic4o 그럼요!! 감사합니다🤗
