### ISSUE TITLE
[Feature]: mapRight

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#299]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils/array

<br />

### **Overview**

기존 map과 다르게 오른쪽부터 callback이 실행되는 함수입니다. 새로운 배열을 반환해야 합니다.

```ts
mapRight([1, 2, 3], (item, index) => item + index);
// [5, 3, 1]
```

**Comment by Gaic4o** [comment]
이번에도 제가 `mapRight` 함수를 구현해 봐도 괜찮을까요? 감사합니다.
