### ISSUE TITLE
[Feature]: isPalindrome

### ISSUE THREAD

**Issue by beberiche** [modern-agile-team/modern-kit#301]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils/string

<br />

### **Overview**

인자로 주어진 문자열이 회문인지 확인하는 함수입니다. `boolean` 을 반환합니다.

```javascript
isPalindrome('기러기'); // true
isPalindrome('기러러러기'); // true
isPalindrome('1a!!a1') // true
isPalindrome('2a!!a1') // false
```

**Comment by ssi02014** [comment]
라이브러리에 지속적으로 관심가져주시고, 추가 이슈 생성해주셔서 감사합니다 😊 
해당 함수가 실무에서 충분히 활용 될 케이스가 있을까요? 약간 알고리즘 로직으로서는 유용할 것 같은데 실무 개발에서도 유용하게 사용 될 케이스가 있을지 궁금합니다 🤗

**Comment by beberiche** [comment]
@ssi02014  아뇨! 실무에 사용되기엔 어려울 듯 합니다! 
다음 이슈를 생성할 때는 실무적인 요소를 신중하게 고민하고 올리겠습니다!!

**Comment by ssi02014** [comment]
@beberiche 빠른 답변 감사드립니다! 해당 이슈는 닫겠지만 지속적인 관심을 가져주신 부분에 대해서 다시 한번 감사의 말씀드립니다! 🙇‍♂️
좋은 아이디어가 있다면 다시 한번 이슈를 생성해주세요 🤗
