### ISSUE TITLE
[Feature]: 조건에 따라 컴포넌트를 렌더링하는 기능

### ISSUE THREAD

**Issue by haejunejung** [modern-agile-team/modern-kit#343]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/react/components

<br />

### **Overview**

개발을 진행하다보면, `조건(condition)`에 따라서, `A`컴포넌트 또는 `B`컴포넌트를 보여줘야 하는 경우가 생기는데요. 
이런 경우에서, 선언적으로 사용하는 방법이 있으면 좋지 않을까 합니다! (`SwitchCase`, `When` 처럼요.)

아래는 간단한 프로토타입을 제작해봤는데요. 유용하다고 생각이 들면, 기능을 구현해서 추가해도 괜찮을까요?

```typescript
type Condition = boolean | (() => boolean);

interface ConditionalComponentProps {
  condition: Condition;
  trueComponent: ReactNode;
  falseComponent: ReactNode;
}

const getConditionalResult = (condition: Condition) => {
  return typeof condition === 'function' ? condition() : condition;
};

export function ConditionalComponent({condition, trueComponent, falseComponent}: ConditionalComponentProps): ReactNode {
  const conditionalResult = getConditionalResult(condition);
  return conditionalResult ? trueComponent : falseComponent;
}
```

**Comment by haejunejung** [comment]
제가 제안한 이유는, `When`과 `ConditionalComponent`가 매우 유사하지만 서로 다른 상황에서 사용될 수 있다고 생각했기 때문이에요. 😊 

# Why?

처음 `When` 컴포넌트를 봤을 때, 다음과 같은 기능을 수행할 것이라고 예상했어요.

```typescript
{condition && <A />}
```

이렇게 생각한 이유는, When 컴포넌트가 조건이 참일 때만 `children`을 렌더링 하고, 거짓일 때는 아무 것도 렌더링하지 않을 것이라고 직관적으로 이해했기 때문이에요. 또한 `fallback`이라는 용어가 일반적으로 조건 실패 시 보여주는 콘텐츠를 의미한다고 생각이 들었어요. 마치 `React`의 `Suspense`처럼요! (내부 코드를 보기전까지요!)

반면, `ConditionalComponent`는 `trueComponent`와 `falseComponent`를 명시적으로 정의하여 조건에 따라 명확하게 컴포넌트를 전환할 수 있지 않을까 생각했어요.

```typescript
{condition ? <TrueComponent /> : <FalseComponent />}
```

제 생각에는 UI가 명확하게 구분되어야 하는 상황, 예를 들어 조건에 따라 전체 UI 조각을 전환해야 할 때 유용하다고 생각이 드는데요. 어떻게 생각하시나요!? 👀

**Comment by ssi02014** [comment]
@haejunejung 무슨 말씀이신지 이해했습니다. 확실히 두 컴포넌트의 동작은 유사하지만 어떤 상황에 쓰이는지와 네이밍을 보고 사용자마다 어떻게 받아들이는지 차이가 있다고 생각합니다. 

이는 좋은 레퍼런스 제공이 될 수 있다고 생각하고, modern-kit에 목적에 부합하다고 생각합니다. 작업 진행해주시면 감사드립니다. 😊
작은 라이브러리지만 관심 가져주셔서 다시 한번 감사의 말씀 드립니다.

**Comment by haejunejung** [comment]
감사합니다:)
