### ISSUE TITLE
[Feature]: swap

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#347]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: `@modern-kit/utils/array`

<br />

### **Overview**

shuffle에 있는 swap 함수를 모듈로서 분리해서 제공합니다.
기본적으로 원본 배열을 변경하지만, 4번째 인자인 immutable 옵션을 true로 주면 원본 배열을 변경하지 않고, 새 배열을 반환합니다.
```ts
const arr = [1, 2, 3]
swap(arr, 0, 2); // [3, 2, 1]
arr // [3, 2, 1]
```
```ts
const arr = [1, 2, 3]
swap(arr, 0, 2, { immutable: true }); // [3, 2, 1]
arr // [1, 2, 3]
```

**Comment by Gaic4o** [comment]
제가 구현 해 봐도 괜찮을까요??!

**Comment by ssi02014** [comment]
@Gaic4o 넵! 감사합니다 shuffle에 기본 swap함수가 있는데 요구사항에 맞게 개선해주시면 감사드립니다 :)
