### ISSUE TITLE
[Feature]: useFocus

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#352]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/react/hooks

<br />

### **Overview**

훅이 반환하는 ref가 할당된 요소가 focus 됐는지 여부를 감지하는 훅입니다. 또한, setFocus로 강제로 focus 할 수 있습니다.
focus, blur 시에 특정 함수를 호출 할 수 있습니다.

```tsx
const { ref, isFocused, setFocus } = useFocus<HTMLInputElement>({ focusAction, blurAction });

<input ref={ref} />
<button onClick={() => setFocus()}>Input 포커스</button>
```

**Comment by 99mini** [comment]
안녕하세요! 해당 기능 구현하여 프로젝트에 기여해도 괜찮을까요?

Overview에 작성해주신 사용법과 인터페이스를 통해서 아래와 같이 설계할 수 있을 것 같습니다.

### interface
```typescript
interface UseFocusProps {
  focusAction?: (event: FocusEvent) => void;
  blurAction?: (event: FocusEvent) => void;
}

interface UseFocusReturnType<T extends HTMLElement> {
  ref: React.RefObject<T>;
  isFocus: boolean;
  setFocus: () => void;
}
```
### Hook
```typescript
function useFocus<T extends HTMLElement>({
  focusAction = noop,
  blurAction = noop,
}: UseFocusProps = {}): UseFocusReturnType<T>
```

### Usage
```typescript
const { ref, isFocus, setFocus } = useFocus<HTMLInputElement>({
    focusAction: () => console.log("포커스"),
    blurAction: () => console.log("포커스 해제"),
});

<input ref={ref} />
<button onClick={() => setFocus()}>trigger focus</button>
<div>{isFocus ? 'Focus' : 'Blur'}</div>
```

### 논의사항

`ref`를 등록하지 않고 해당 훅을 사용할 때 throwable한 훅을 설계하는 것이 좋을 지, 아니면 아무 행동도 하지 않게 하는 게 좋을 지 궁금합니다.

**Comment by ssi02014** [comment]
@99mini @modern-kit 에 관심가져주셔서 감사합니다! 네 당연히 작업해주셔도 좋습니다

> ref를 등록하지 않고 해당 훅을 사용할 때 throwable한 훅을 설계하는 것이 좋을 지, 아니면 아무 행동도 하지 않게 하는 게 좋을 지 궁금합니다.

아무런 동작하지 않게끔 설계하는게 좋을 것 같습니다. 구현 복잡도를 줄이는 것도 있지만, ref가 할당되지 않으면 아무런 동작하지 않게끔 통일성있게하기 위함입니다

**Comment by 99mini** [comment]
> 아무런 동작하지 않게끔 설계하는게 좋을 것 같습니다. 구현 복잡도를 줄이는 것도 있지만, ref가 할당되지 않으면 아무런 동작하지 않게끔 통일성있게하기 위함입니다

넵! 감사합니다. 구현하여 PR 작성하도록 하겠습니다~!
