### ISSUE TITLE
[BUG]: @modern-kit/types

### ISSUE THREAD

**Issue by haejunejung** [modern-agile-team/modern-kit#356]
@ssi02014 Repository 구조를 이해하면서 생긴 궁금증과 어디까지 버그로 봐야할 지를 이해하고자 이슈를 열었습니다. 설명해주시면 감사하겠습니다 🙏

### Package Scope

- Package name: @modern-kit/types

<br />

### **버그 요약 설명**

 

- docs에 `@modern-kit/types`가 없어요.  의도된 것인지 궁금해요. 👀 
![image](https://github.com/user-attachments/assets/5588589d-587e-43f2-bfc7-e18005ab621f)

- packages/types에서 제공되는 README파일에 `@modern-kit/utils`로 적혀있어요. `@modern-kit/types`로 수정이 필요해보여요.
![image](https://github.com/user-attachments/assets/90f3f842-f568-470d-af5b-5a5d1083baad)

- bundlephobia에 `@modern-kit/types`가 검색이 되지 않는 것 같아요.
![image](https://github.com/user-attachments/assets/b493dea9-aea2-4b20-b5b6-59a857b4b004)

**이를 비롯하여 전체적으로 `@modern-kit/types`에 많은 부분이 `@modern-kit/utils`과 혼동되어 있는 것 같아요. `internal`에서만 사용하기 위한 목적인지, 혹은 `@modern-kit/utils`와는 다르게 제공하고 싶은 기능인지 궁금해요! 👀** 

<br />

### **예상되는 동작**

<br />

### **재현 코드 혹은 설명**

```ts
// code
```

<br />

### **가능한 해결책**

```ts
// code
```

**Comment by ssi02014** [comment]
@haejunejung 이슈 올려주셔서 감사합니다!
아직 modern-kit은 문서와 같은 디테일한 부분에서 정비가 필요한 상태입니다. 저는 지속적으로 modern-kit을 디벨롭해 나갈 예정입니다.
그 전까지는 약간의 불편함을 드릴 수 있어 사전에 죄송하다는 말씀드립니다. 🙏

1. 현재는 계획되어 있지 않지만, 추가 할 예정입니다. 현재는 utils와 react에 집중하고 있습니다. 어느정도 정비가 완료되면 types도 개선 예정입니다.
2. 수정이 필요한 부분입니다.
3. 확인이 필요한 부분입니다.

> 이를 비롯하여 전체적으로 @modern-kit/types에 많은 부분이 @modern-kit/utils과 혼동되어 있는 것 같아요. internal에서만 사용하기 위한 목적인지, 혹은 @modern-kit/utils와는 다르게 제공하고 싶은 기능인지 궁금해요! 👀

위 질문은 types는 modern-kit 내부적으로 internal로 사용하기 위함도 있지만 유용하게 쓰일 법한 `유틸 타입`들을 모듈로서 or 레퍼런스로 제공하기 위함입니다.

**Comment by haejunejung** [comment]
확인해주셔서 감사합니다 😄

`@modern-kit/types`에 대한 문서화 작업이 필요한거라면 하나씩 진행해도 괜찮을까요? 👀 

이유는, 이 패키지에 새로운 기능을 추가해야 하는 상황이 왔을 때, docs를 작성해야 하는지에 대해서 의문이 들 것 같아요.

**Comment by ssi02014** [comment]
@haejunejung 작업을 해주신다면 감사드립니다.
제가 문서를 하나 추가하고 말씀드리겠습니다. 이후에 추가된 문서를 참고해서 작업해주시면 좋을 것 같습니다
