### ISSUE TITLE
[Feature]: isNumricString

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#357]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils/validator

<br />

### **Overview**

주어진 문자열 인자가 숫자로만 구성되어 있는지 판단합니다.

```ts
isNumericString('123'); // true
isNumericString('1'); // true
```
```ts
isNumericString(""); // false
isNumericString("   "); // false
isNumericString('d111'); // false
isNumericString('111d'); // false
isNumericString('11d1'); // false
```

**Comment by haejunejung** [comment]
`isNumber`가 기존 `@modern-kit/utils`에서 제공되고 있는 것으로 확인했는데요. `isNumber`에 해당 기능을 추가(보완)하는 것이 아니라 `isNumericString`으로 제공하려는 이유가 무엇인지 궁금합니다! 👀 

기존의 `isNumber`:
```typescript
export const isNumber = (arg: unknown): arg is number => {
  return typeof arg === 'number';
};
```

**Comment by ssi02014** [comment]
@haejunejung 댓글 감사드립니다 🤗 해당 isNumber는 주어진 인자가 숫자형 타입(number)인지를 판단하기 위한 함수이며,
이번에 올린 isNumericString 함수는 인자로 문자열만을 받아올 수 있으며, 해당 문자열이 숫자로만 구성되어 있는지 판단하기 위함입니다 🤗

```ts
isNumber(123); // true
isNumber(new Set()); // false
isNumber(''); // false
isNumber({}); // false
```
```ts
isNumericString('123'); // true
isNumericString('1'); // true
```

**Comment by haejunejung** [comment]
@ssi02014 설명 감사합니다 🙏 

해당 `isNumericString`에서의 문자열의 경우 `Integer`만 판단하는 것인가요? 아니면 `number`에 대해서 판단하는 것인가요?

위의 정규표현식을 사용한다면, Integer에 대해서만 가능할 것으로 보여서요! 
```typescript
// 정규 표현식 사용시 
const value = '12.123'
isNumericString(value) // false
```
`number`에 대해서 모두 허용하고자 하는 거라면 아래와 같은 구현 방식은 어떤가요? `Number`의 경우, 문자열이나 다른 값을 Number 타입으로 변환하는 기능을 제공하는데요. 만약 인수를 숫자로 변환할 수 없으면 `NaN`을 리턴하는 것을 이용하면 어떨까 합니다!

Reference: [MDN Number](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Number)
```typescript
// isNaN, Number 사용시
export function isNumericString (value: string): boolean {
  return !isNaN(Number(value))
}
const value = '12.123'
isNumericString(value) // true
```

**Comment by ssi02014** [comment]
@haejunejung `Integer`경우만 판단하고자 합니다 🙏
문자열이 온전히 숫자로만 포함되어 있는지를 판단하는 것이 목적입니다

**Comment by haejunejung** [comment]
설명 감사합니다.

제가 `isNumericString`에 대해서 위의 구현을 바탕으로 문서와 테스트를 작성해봐도 괜찮을까요? 👀

**Comment by ssi02014** [comment]
@haejunejung 물론입니다! 지속적인 관심 정말 감사드립니다
