### ISSUE TITLE
[Feature]: serialize

### ISSUE THREAD

**Issue by Sangminnn** [modern-agile-team/modern-kit#370]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils/string

<br />

### **Overview**

serialize는 string 형태의 URL, URL 객체, URL SearchParams 에 안전하게 쿼리를 연결할 수 있도록 합니다.

연결하고자하는 쿼리는 객체형태로 받아 이를 간단한 인터페이스를 통해 연결하여 사용할 수 있도록 합니다.

해당 함수에 단일 객체만 넘기는 경우 해당 객체의 값들로 search params를 만들어 반환해줍니다.

```tsx
// 예상 인터페이스
export function serialize(values: Record<string, any>): string
export function serialize(base: Base, values: Record<string, any>): string
export function serialize(baseOrValues: Base, values: Record<string, any> = {})


// 예상 결과값
serialize({ str: 'zxcv', num: 1 }) // '?str=zxcv&num=1'

serialize('https://example.com?search=asdf', { str: 'zxcv' }) // 'https://example.com?search=asdf&str=zxcv'

const search = new URLSearchParams('?bar=good')
serialize(urlSearchParams, { str: 'zxcv' }) // '?bar=good&str=zxcv'

const url = new URL('https://example.com/path?bar=good')
serialize(url, { str: 'zxcv' }) // 'https://example.com/path?bar=good&str=zxcv'
```

## 고민 포인트

1. 동일한 key에 대한 value가 들어온다면 이를 override해줄지 동일한 key로 연결해줄지?
2. 위와 같은 정책을 사용하는 유저가 선택할 수 있도록 위임한다면, 이에 대한 옵션을 어떻게 받을지?
3. 위의 유틸함수가 실제로 유틸로서 추출할만큼 효용성이 있을것인지

### 2번에 대한 부연설명

2-1. value와 search를 받아서 처리하는 현재의 인터페이스에서 옵션까지 받고자한다면 두번째 인자로 들어오는 객체를 value, options 과 같이 세분화해야할텐데, 이렇게될 경우 기존과 다르게 인터페이스가 복잡해지는 문제
2-2. 위와 같은 옵션을 제공한다면 네이밍은 어떻게 하는 것이 가장 자연스러울지? (ex. 'override' | 'keep')

```tsx

// as-is
serialize('https://example.com', { str: 'asdf' }

// to-be?
serialize('https://example.com', {
  value: { str: 'asdf' },
  options: 'override'
}
```

**Comment by Sangminnn** [comment]
@ssi02014 위에 대한 고민을 해보았는데 작업해도 괜찮을지에 대해 천천히 살펴봐주시면 감사드리겠습니다! 😄

**Comment by Sangminnn** [comment]
@ssi02014 좋은 의견 감사합니다! 말씀주신것처럼 아무래도 받은 값에 추가적으로 처리를 하려다보니 고민포인트가 많아지는것같네요! 😂 
해당 스펙들은 제거하고 제안주신 방향으로 한번 함수를 만들어보겠습니다! 👍

**Comment by ssi02014** [comment]
@Sangminnn 긍정적으로 봐주셔서 감사합니다😄😄👍👍👍
