### ISSUE TITLE
[Feature]: useDependencyTimeout

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#372]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/react/hooks

<br />

### **Overview**

useTimeout을 재사용해 원하는 의존성 값이 변경되면 timeout을 재설정하는 커스텀 훅입니다.

```ts
/*
  callback: 실행 할 콜백
  delay: timeout delay
  deps: 의존성 배열
  callOnMount: 최초 마운트 시에 callback 호출 할 것인지 결정
*/
useDependencyTimeout(callback, delay, deps, { callOnMount });
```

**Comment by Collection50** [comment]
안녕하세요 @ssi02014 !

오랜만에 인사드려요 !

이 작업을 제가 담당해도 될까요?

**Comment by ssi02014** [comment]
@Collection50 당연합니다😄 꾸준한 관심 감사드립니다!
