### ISSUE TITLE
[Feature]: pickFalsy

### ISSUE THREAD

**Issue by Sangminnn** [modern-agile-team/modern-kit#374]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils/common

<br />

### **Overview**

문득 여러가지 falsy값중에서 일부만 골라서 사용하고싶은 경우 명시적으로 나열하는 것이 번거롭다고 느껴졌습니다.

예를 들어, API로부터 받아온 데이터의 타입을 체크하는데 return값이 숫자이지만 0은 상황 상 정상적인 값이라면 편하게 falsy로 체크하고싶지만 0의 케이스가 걸리기때문에 조금 번거로워질듯 합니다.

이를 특정 함수를 통해 체크하고싶은 falsy값만 골라 반환받은 함수를 사용하는 방식이 있으면 어떨까 생각이 들었네요! 😂 

예상 인터페이스 및 사용방식은 다음과 같습니다.

```typescript
// 커스텀으로 빈 배열이나 빈 객체에 대한 체크도 넣을수 있겠다 싶긴했네요 🤔 
type PickFalsyProps = 'boolean' | 'null' | 'undefined' | 'number' | 'string' 
const isInvalidValue = pickFalsy('boolean' | 'null')

if(isInvalidValue(input)) {
	// do something ..
}
```

**Comment by Sangminnn** [comment]
@ssi02014 간단한 아이디어이기때문에 천천히 보시고 의견주시면 감사드리겠습니다! 🙇

**Comment by ssi02014** [comment]
@Sangminnn 
너무 좋은 기능같습니다! 아무래도 boolean 값이 아닌 함수를 반환하니 validator의 역할보다는 `utils/common`에 추가되도 좋을 것 같긴하네요

동작을 제가 이해한게 맞는지 한번 확인해주시면 감사드립니다
```ts
const isInvalidValue  = pickFalsy('boolean', 'null'); // boolean과 null에 대한 값만 검증

isInvalidValue(false); // true
isInvalidValue(null); // true

isInvalidValue(0); // false
isInvalidValue(''); // false
```

```ts
const isInvalidValue  = pickFalsy('boolean', 'null', 'number'); // boolean, null, number에 대한 값만 검증

isInvalidValue(false); // true
isInvalidValue(null); // true
isInvalidValue(0); // true

isInvalidValue(''); // false
```

**Comment by Sangminnn** [comment]
@ssi02014 긍정적으로 봐주셔서 감사합니다! 😄 

동작은 이해하신 바와 동일하며 기존에는 특정 상황에 대한 검증에 포커스를 맞추어 validator로 생각했으나, 말씀주신 바와 같이 함수를 반환한다는 점에서 common으로 들어가도 좋겠네요!

요 함수도 한번 작업해서 공유드려보겠습니다! 🙇

**Comment by ssi02014** [comment]
@Sangminnn 추가로 고민되는게 `false`, `null`, `undefined`, `NaN`는 너무나 당연한 falsy 한 값들이라 그냥 옵션으로 받을 필요 없이 기본적으로 처리해도 좋을 것 같기도하네요!
옵션으로 처리하면 좋을게 (array, object, string, number)
`빈 배열([])`, `빈 객체({})`, `0`, `빈 문자열('')` -> 이를 다루는게 어떨까 싶습니다!

**Comment by Sangminnn** [comment]
@ssi02014 오오 좋은 의견 감사합니다! 말씀 주신 방향으로 한다면 기본적으로 체크하는 케이스는 번거롭게 추가하지 않아도 괜찮고, 최초에 고민했던 빈 배열과 빈 객체에 대한 부분도 처리할 수 있어서 더 좋아보이네요! 

주신 의견 잘 반영하겠습니다! 👍👍👍
