### ISSUE TITLE
[Feature]: compact

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#399]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils/array

<br />

### **Overview**

falsy한 값(0, '', null, NaN, undefined)을 모두 제거하는 배열입니다.

```ts
compact([0, 1, false, 2, '', 3, null, undefined, 4, NaN, 5]);
// [1, 2, 3, 4, 5]
```

**Comment by Gaic4o** [comment]
제가 구현 해 봐도 괜찮을까요!?

**Comment by ssi02014** [comment]
@Gaic4o 그럼요!! 감사합니다🤗🤗
