### ISSUE TITLE
[Feature]: xor

### ISSUE THREAD

**Issue by ssi02014** [modern-agile-team/modern-kit#438]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/utils/array

<br />

### **Overview**

사용자 지정 매핑 함수를 사용하여 두 배열 간의 대칭 차이(xor)를 계산합니다.
대칭 차이는 두 배열 중 하나에 있는 요소의 집합입니다. 필요 시 3번째 인자인 iteratee 함수 결과로 대칭 차이 요소임을 판단 할 수 있습니다.

```ts
xor([1, 2], [2, 3]);
// [1, 3]

xor([{ id: 1 }, { id: 2 }], [{ id: 2 }, { id: 3 }], (x) => x.id);
// [{ id: 1 },  id: 3 }]
```

**Comment by Gaic4o** [comment]
제가 구현 해 봐도 괜찮을까요~?

**Comment by ssi02014** [comment]
@Gaic4o 좋아요 :) !!감사합니다
