### ISSUE TITLE
[Feature]: ClientGate

### ISSUE THREAD

**Issue by Sangminnn** [modern-agile-team/modern-kit#513]
### **Package Scope**

- [ ] 기존 패키지에 기능 추가
- [x] 새로운 패키지
- Package name: @modern-kit/react/components

<br />

### **Overview**

기존의 ClientOnly 에서 보다 최적화된 형태로 Next.js와 같은 Hydration이 존재하는 환경에서 유의미합니다.

기존의 ClientOnly의 경우 Mount 이후의 시점을 기준으로 렌더링을 수행하기때문에 Only CSR 환경에서는 바로 화면에 그려줄 수 있는 컴포넌트임에도 불구하고 렌더링 사이클의 실행 시점까지 딜레이됩니다.

ClientGate를 활용하면 SSR, Hydration 단계에서는 기존과 동일하게 fallback component를 보여주고, Pure CSR 환경에서는 렌더링 사이클 이전에 즉시 해당 컴포넌트를 반환해줍니다.

ClientOnly에서와 같이 마운트 이후의 시점을 캐치하여 보여주고자 하는 니즈도 있을 것으로 보여 별도의 컴포넌트를 설계하는 것으로 고민했습니다.

해당 훅은 SnapShot에서의 반환값이 참조가 아닌 값이기때문에 무한 호출은 일어나지 않을 것으로 생각됩니다.

```typescript
interface ClientGateProps {
  fallback?: JSX.Element;
}

export const ClientGate = ({
  fallback = <></>,
  children,
}: React.PropsWithChildren<ClientGateProps>) => {
  const isServer = useSyncExternalStore(
    emptySubscribe,
    () => false,
    () => true
  );

  return isServer ? fallback : children();
};

```

**Comment by Sangminnn** [comment]
@ssi02014 해당 작업에 대해 한번 검토해주시면 감사드리겠습니다! 😃

**Comment by ssi02014** [comment]
@Sangminnn 검토 후에 빠른 시일 내로 의견을 남기도록 하겠습니다! 감사합니다 😀

**Comment by ssi02014** [comment]
@Sangminnn useSyncExternalStore 을 활용해서 렌더링 사이클 이전에 컴포넌트를 반환하면서, 의도대로 동시에 클라이언트 환경을 보장해주는 좋은 의견이라고 생각합니다.

단, 개인적으로는 ClientOnly 컴포넌트의 목적 자체가 Client에서 랜더링을 보장해주는게 목적이지, 사실 렌더링 사이클 이후에 렌더링되야 한다를 보장한다는 아니기 때문에 만약 마운트 이후에 렌더링을 보장해주는 컴포넌트의 경우에는 별도의 컴포넌트를 생성하는게 나을 수도 있겠다는 생각입니다. 

 - ex: `<Mounted>{children}</Mounted>`

즉, 제가 제안드리는 내용은 다음과 같습니다. 좋은 의견주시면 감사드립니다!
1. ClientGate 신규 컴포넌트 추가, ClientOnly 컴포넌트는 Deprecated
2. ClientOnly 자체를 변경
3. 마운트 이후에 렌더링한다는 명확한 목적을 가진 Mounted 신규 컴포넌트 추가
