### ISSUE TITLE
[Feature]: NonEmptyArray

### ISSUE THREAD

**Issue by Sangminnn** [modern-agile-team/modern-kit#528]
### **Package Scope**

- [x] 기존 패키지에 기능 추가
- [ ] 새로운 패키지
- Package name: @modern-kit/types

<br />

### **Overview**

```typescript
type NonEmptyArray<T> = [T, ...T[]]

const array1: NonEmptyArray<string> = [] // error!!
const array2: NonEmptyArray<string> = ['asd']  // Ok!
```

해당 Array가 비어있지 않을 수 있도록 체크하는 타입입니다.

**Comment by Sangminnn** [comment]
@ssi02014 요 부분 작업해도 괜찮다면 제가 담당하겠습니다! :)

**Comment by ssi02014** [comment]
@Sangminnn 넵! 좋습니다 :)

**Comment by ssi02014** [comment]
@Sangminnn 앞으로 테스트 코드 설명도 한국어로 작성해주시면 감사드립니다. 작업 시 참고부탁드립니다.
https://github.com/modern-agile-team/modern-kit/issues/532

**Comment by Sangminnn** [comment]
@ssi02014 내용 확인했습니다! 공지해주셔서 감사합니다!! 👍
