### ISSUE TITLE
[BUG]:useThrottle 

### ISSUE THREAD

**Issue by rhehfl** [modern-agile-team/modern-kit#586]
### Package Scope

- Package name:@modern-kit/react/hooks

<br />

### **버그 요약 설명**

- `useThrottle`의 제네릭으로 리턴타입의 타입을 지정해주었는데 any타입으로 추론되는 버그가 있는 것 같습니다.

<br />

### **예상되는 동작**
- `useThrottle`이 리턴하는 함수가 any타입으로 추론되어 타입 안정성이 낮아지는 것 같습니다

<br />

### **재현 코드 혹은 설명**
- ![image](https://github.com/user-attachments/assets/43e40314-aa7a-4a64-9ac0-744704f0d933)

 ```ts
export function useThrottle<T extends ThrottleParameters[0]>(
  callback: T,
  wait: ThrottleParameters[1],
  options: ThrottleParameters[2] = {}
): ThrottleReturnType<T> {
  const callbackAction = usePreservedCallback(callback);
  const preservedOptions = usePreservedState(options);

  // useMemo에 제네릭을 명시하여 throttled의 타입을 정확하게 추론하도록 합니다.
  const throttled = useMemo(() => {
    return throttle(callbackAction, wait, preservedOptions);
  }, [callbackAction, wait, preservedOptions]);

  // 언마운트 시 쓰로틀 된 함수의 보류 중인 호출을 모두 버립니다.
  useUnmount(() => throttled.cancel());

  return throttled;
}
```
내부적으로는  `ThrottleReturnType<T>`타입으로 리턴타입을 지정해주는 것 같은데 의도하신 리턴타입은 아닌 것 같아 버그 이슈를 올립니다!

<br />

### **가능한 해결책**

```ts
export function useThrottle<T extends ThrottleParameters[0]>(
  callback: T,
  wait: ThrottleParameters[1],
  options: ThrottleParameters[2] = {}
): ThrottleReturnType<T> {
  const callbackAction = usePreservedCallback(callback);
  const preservedOptions = usePreservedState(options);

  // useMemo에 제네릭을 명시하여 throttled의 타입을 정확하게 추론하도록 합니다.
  const throttled = useMemo<ThrottleReturnType<T>>(() => {
    return throttle(callbackAction, wait, preservedOptions);
  }, [callbackAction, wait, preservedOptions]);

  // 언마운트 시 쓰로틀 된 함수의 보류 중인 호출을 모두 버립니다.
  useUnmount(() => throttled.cancel());

  return throttled;
}
```
- `useMemo` 의 제네릭으로 `ThrottleReturnType<T>`를 전달하여 `throttled `타입을 확실하게 해주면 어떨까 싶습니다.

**Comment by ssi02014** [comment]
@rhehfl 저의 경우에는 제대로 타입 추론이 되고 있는 상황인데요. 
### 사례
![스크린샷 2024-11-18 오전 12 21 19](https://github.com/user-attachments/assets/8aaae7f0-6d41-48a0-9be1-74865c9783eb)

### ThrottleReturnType
<img width="892" alt="스크린샷 2024-11-18 오전 12 23 17" src="https://github.com/user-attachments/assets/a5620de8-38ed-4395-9d75-2ff41209d532">

<br />

제가 예상하는건 현재 lodash-es가 사용자 측에서 없을 경우 타입 추론이 제대로 되지 않는 다는 것입니다.
저의 경우에도 lodash-es가 없는 상태에서 modern-kit을 사용할 경우 이슈가 발생하네요.

이 경우에는 예상하기로는 lodash-es가 현재 devDependencies 포함되어 있기 때문입니다.

<br />

PR: https://github.com/modern-agile-team/modern-kit/pull/587
해당 PR에서 lodash-es의 위치를 dependencies 로 변경하였습니다. 이 변경 사항은 modern-kit/react v1.24.0 에 포함 될 예정입니다. 
배포하게 되면 다시한번 확인해주시면 감사드립니다.

**Comment by ssi02014** [comment]
devDependencies 에서 dependencies lodash-es를 옮겼음에도 현상이 동일해 @types/lodash-es도 dependencies에 포함하였습니다.

**Comment by ssi02014** [comment]
@rhehfl @modern-kit/react v1.24.1 에서 해결된 것으로 보입니다 :) 확인해주시면 감사드립니다.
- 당장에 예정되어 있지는 않지만 추후 계획으로 lodash-es를 걷어낼 수 있도록 작업하려고 합니다 감사합니다

**Comment by rhehfl** [comment]
@ssi02014 확인했습니다
사용자 측에서 ` lodash-es`가 의존성으로 설치되어 있어야 타입추론이 되는거였군요! 꼼꼼하게 확인해주셔서 감사합니다😊
다만 ` @modern-kit/react v1.24.1` 버전을 설치한 후 다시 확인해보려는데 
1.23.0버전의 경우에는 설치가 잘 되는 반면에 다음과 같이 `1.24.1` 버전에서만 이러한 설치 오류가 발생하는 것 같습니다..
![image](https://github.com/user-attachments/assets/3e91587a-f8f4-4079-b101-a74a5d4751e0)
한번 확인해주시면 감사할 것 같습니다!

**Comment by ssi02014** [comment]
@rhehfl npm은 workspace를 지원하지 않는 것으로 보입니다. yarn은 지원을 합니다.
- https://stackoverflow.com/questions/69220042/npm-err-unsupported-url-type-workspace-workspace 
우선 이 부분도 npm도 지원할 수 있게 재수정이 필요해보이네요

**Comment by rhehfl** [comment]
아하
빠른 답변 감사합니다!
yarn을 사용해서 설치를 해봐야겠네요 감사합니다!!😁

**Comment by ssi02014** [comment]
@rhehfl 우선 1.24.2 로 재배포했습니다. 다시 확인해주시면 감사드립니다~!

**Comment by rhehfl** [comment]
확인했습니다
![image](https://github.com/user-attachments/assets/3f4fbd29-5f07-4cdb-a988-169bf93e92da)
1.24.2버전으로 설치하니 npm으로도 잘 설치되고 타입추론도 잘 되네요!!!
감사합니다~~!😊

**Comment by ssi02014** [comment]
@rhehfl 확인 감사합니다 해당 이슈는 닫도록 하겠습니다 :)
